In [14]:
import tensorflow as tf
import numpy as np
import pandas as pd
import tensorflow_datasets as tfds

In [29]:
train_path = '/Users/yujin/Desktop/python_projects/머신러닝교과서/datasets/Baseline Code + Data/train_data.csv'
test_path = '/Users/yujin/Desktop/python_projects/머신러닝교과서/datasets/Baseline Code + Data/test_data.csv'

df_test = pd.read_csv(test_path)
df_train = pd.read_csv(train_path)
df_train.isnull().sum()

reviewer_id      0
store_name       0
category         0
store_address    0
latitude         0
longitude        0
rating_count     0
review_time      0
review           0
rating           0
dtype: int64

In [30]:
df_train.shape

(26188, 10)

In [31]:
target = df_train.pop('rating')

In [32]:
import re
# 특수 문자를 제거하는 함수 정의
def remove_invalid_chars(text):
    return re.sub(r'[^\x00-\x7F]+', '', text)

# review 컬럼에서 특수 문자 제거
df_train['review'] = df_train['review'].apply(remove_invalid_chars)
review = df_train.pop('review')
review.head(5)

0    The manager is rude and speaks to her employee...
1                                                Good 
2    What a waste of time we were there in line for...
3        Drive through was smooth and service was good
4                                           Excellent 
Name: review, dtype: object

In [33]:
import myprocess

padded_sequences, token_counts = myprocess.preprocessing_tokinize(review)

In [35]:
len(token_counts)
padded_sequences

array([[   0,    0,    0, ...,  839,    6, 3740],
       [   0,    0,    0, ...,    0,    0,   19],
       [ 206,   69,    1, ...,  315,  337,  239],
       ...,
       [   0,    0,    0, ...,   26,  269,  427],
       [   0,    0,    0, ...,    0,    0,   46],
       [   0,    0,    0, ...,    0,  159,   75]], dtype=int32)

In [41]:
review_tensor = tf.convert_to_tensor(padded_sequences, dtype=tf.float64)
target_tensor = tf.convert_to_tensor(target.values, dtype=tf.float64)

ds_raw = tf.data.Dataset.from_tensor_slices((review_tensor, target_tensor))

# 결합된 데이터셋의 샘플 확인
for features, label in ds_raw.take(3):
    tf.print(features[:10], label)

[0 0 0 ... 0 0 0] 1
[0 0 0 ... 0 0 0] 4
[206 69 1 ... 99 10 97] 1


2024-08-10 11:45:52.271594: I tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


In [42]:
process = myprocess.PreProcess(ds_raw, target.shape[0], is_tokenize=True)
len(token_counts)

12917

In [43]:
batch_size = 32

train_data, valid_data, test_data = process.get_datas(batch_size, train_size=0.5, valid_size = 0.1, test_size=0.4)

In [44]:
vocab_size = len(token_counts) + 2  
node_nums = [32, 64]
embedding_dims = [75, 100, 150, 200]
layer_nums = [1, 2]

model_list= myprocess.make_models(vocab_size, node_nums, embedding_dims, layer_nums)
model_list

[<Sequential name=sequential, built=False>,
 <Sequential name=sequential_1, built=False>,
 <Sequential name=sequential_2, built=False>,
 <Sequential name=sequential_3, built=False>,
 <Sequential name=sequential_4, built=False>,
 <Sequential name=sequential_5, built=False>,
 <Sequential name=sequential_6, built=False>,
 <Sequential name=sequential_7, built=False>,
 <Sequential name=sequential_8, built=False>,
 <Sequential name=sequential_9, built=False>,
 <Sequential name=sequential_10, built=False>,
 <Sequential name=sequential_11, built=False>,
 <Sequential name=sequential_12, built=False>,
 <Sequential name=sequential_13, built=False>,
 <Sequential name=sequential_14, built=False>,
 <Sequential name=sequential_15, built=False>]